### PR TITLE
R7 Semyorka part price fix

### PR DESCRIPTION
**Pull request by speedwaystar**
this brings the price of the completed R7 Semyorka Block A + B to around the same as the equivalent Bobcat Industries and Tantares versions of R7. for comparison:

RN R7 = 59300
Bobcat R7 = 65000
Tantares R7 (x2) = 58100 (the Tantares is 1.25m)
Home Grown Rockets R7 ~=42000

i've checked all the other R7 parts and they're well within the normal range for parts of their type.

i'll do the RN Proton etc once i get up to them in the Historical Missions progression :)

### CODE REVIEW

**Comment by raidernick** [comment]
Was there something wrong with this? The only things I noticed were I already updated firespitter to 1.1 and you don't need to change the tech tree with a mm config you can edit the files directly.

**Comment by speedwaystar** [comment]
I thought I might as well hold off on the PR until I've done some more work.

the mm cfg makes it easier for me to group the parts by era and keep track
of what I have and haven't changed. ultimately if your happy with the
changes I'll convert them to file edits.

**Comment by speedwaystar** [comment]
update: i've priced all the parts in all your packs (mostly using the values from RP-0) and put everything in appropriate tech nodes . now i have to figure out an easy way to convert the modulemanager patches i used to do this to actual file edits. probably have to write a perl script.

**Comment by Mecaguy03** [comment]
What is the status of the price fix now? If you need the actual files edited I can do that for you, if you provide the changes I would need to make.

**Pull request closed without merging**
